apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: origenai/cloud-engineer-test-sample-app-backend:1.0.0
        ports:
        - containerPort: 3001
        env:
        # I set noauth because this backend line doesn't let me override the mongo endpoint so I can use uri to Auth mongoose.connect("mongodb://mongo:27017/todos"
        # - name: MONGO_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secrets
        #       key: MONGO_INITDB_ROOT_USERNAME
        # - name: MONGO_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-secrets
        #       key: MONGO_INITDB_ROOT_PASSWORD
        # - name: MONGODB_URI
        #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017/todos?authSource=admin"
        - name: HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
